### ISSUE TITLE
does it support client-server mode realtime STT?

### ISSUE THREAD

**Issue by Snow9666** [KoljaB/RealtimeSTT#10]
Hi, KoljaB

   Thanks for your contribution. I learned a lot although I'm still a newbie.
   I have a application scenario ：
         _A linux machine with Nvidia GPU, I want use it (as server) to **realtime** transtribe audio from macbook( as client) ;_ 
   Does this object support this application scenario?

Regards,
Snow

**Comment by KoljaB** [comment]
Thx, currently not yet supported. But I love the idea and I think I can deliver this in the next dass.

**Comment by awesome-gpt4** [comment]
@KoljaB : Shouldn't this issue be marked closed since you've implemented this?: https://github.com/KoljaB/RealtimeSTT/tree/master/example_webserver

> I think I can deliver this in the next days.
Or did I misunderstand what you wanted to deliver?

**Comment by KoljaB** [comment]
Oh, you're right, but it's this demo:

[https://github.com/KoljaB/RealtimeSTT/tree/master/example_browserclient](https://github.com/KoljaB/RealtimeSTT/tree/master/example_browserclient)

This one records audio from the client's microphone, the other one from the server. 

It's implemented since [v0.1.8](https://github.com/KoljaB/RealtimeSTT/releases/tag/v0.1.8).
