### ISSUE TITLE
How to recognize the voices of speakers in the multi-speaker scenario

### ISSUE THREAD

**Issue by jacobtang** [KoljaB/RealtimeSTT#25]
How to recognize the voices of speakers in the multi-speaker scenario,for example, in a multi-person meeting scenario?one speaker user assigned one AudioToTextRecorder instance? Thanks！

**Comment by KoljaB** [comment]
Short answer: that is basically currently not possible, at least not in the opensource world. 

Long answer: Deepgram has a quite potent speaker diarization but it's a payed service. The best opensource speaker diarization model currently is from pyannote audio (as of my knowledge). I tried different stuff for my [https://github.com/KoljaB/TurnVoice](https://github.com/KoljaB/TurnVoice) project, but tbh they all disappoint in some ways. There are lots of situations for all models I tried where the diarization failed and a human would easily make it right.

**Comment by alkeryn** [comment]
@KoljaB it is possible, just not as straightforward to use as realtime stt and not sure if you could do it realtime
https://github.com/MahmoudAshraf97/whisper-diarization/
https://github.com/transcriptionstream/transcriptionstream
https://github.com/Haschtl/transcripy
https://github.com/stanleyshen2003/multispeaker_transcription
https://github.com/m-bain/whisperX

still i'm living these links here for future reference both for other people and myself.

**Comment by alkeryn** [comment]
@KoljaB thank you for your reply, it would indeed be amazing to be able to do it realtime !
yea no hurry, we aren't entitled to your time, realtime stt is already super useful as is !

though i'm already using it by feeding it the pcm data myself, and i already have silero vad setup in my codebase too so maybe i could find some way to tag audio before feeding it, that'd be pretty great.

i know there is also the qwen audio model, which can recognize different speakers but then you have to worry about it not forgetting speakers because of context size.

anyway, this is not my field of expertise but i'd imagine something like a vector space with voice fingerprint and you can use cosine similarity to tag voices.

this would not be ideal for mixed voice streams, but it being able to differenciate voices when not mixed would still be better than not at all.

**Comment by KoljaB** [comment]
That is exactly the approach I used for WhoSpeaks. I thought that was original and new until I found out Hervé basically does the same in pyannote audio lol
