### ISSUE TITLE
Imput device: what you hear

### ISSUE THREAD

**Issue by aVitomin** [KoljaB/RealtimeSTT#42]
Good afternoon, is there any possibility to install an imput device on what you hear?
I am considering this program to transcribe in real time the entire conversation between several people I hear, is it possible?

**Comment by aVitomin** [comment]
Rather the question is different, can I use multiple "input_device_index" my microphone and speakers?

**Comment by KoljaB** [comment]
On Windows you can enable "Stereo Mix" in your sound settings, which allows you to use it as an input device that combines different audio sources. Not all sound cards support this feature. And no clue about other platforms.

**Comment by KoljaB** [comment]
You can retrieve the raw recorded audiobytes used for the transcription after speech was detected in recorder.last_transcription_bytes. You can save that to file (when saving as wave you need to add int 16 mono 16000 Hz wave headers) so you have the recorded audio for the conversation. Is that what you mean?

**Comment by aVitomin** [comment]
I want to use it to transcribe speech during a conversation and translate it later.

3 people in the voice channel
1. - The first one speaks in his own language.
2. we get a live transcription
3. - The second person translates the transcription into another language.
4. - The third person responds in their own language
5. we get a live transcription
6. - Second person translates the transcription into another language
repeat

**Comment by KoljaB** [comment]
I'd use something like [this](https://github.com/KoljaB/RealtimeSTT/blob/master/tests/realtimestt_test.py) as a base. This is what is used for the demo video on the front page of this repo.  

I'd change this code to:
- remove the line 'language': 'en', since you want to transcribe multilanguage
- if you want to see realtime transcription change 'realtime_model_type' to 'base', 'small', 'medium' or any other multilanguage model; if you don't want to use realtime transcription remove all the parameters starting with 'realtime_'
- save any detected text to a file in process_text so you don't need to copy paste from the window and can add timestamps etc
- eventually adjust some parameters depending on the speakers speed etc (min_gap_between_recordings, post_speech_silence_duration, min_length_of_recording etc)

**Comment by KoljaB** [comment]
Btw you could also use a LLM to do a automatic translation like done here:
https://github.com/KoljaB/RealtimeSTT/blob/master/tests/translator.py

Or you can use google translate like here:
https://github.com/KoljaB/TurnVoice/blob/main/turnvoice/core/translate.py

**Comment by aVitomin** [comment]
I want to use it to transcribe speech during a conversation and translate it later.

3 people in the voice channel
1. - The first one speaks in his own language.
2. we get a live transcription
3. - The second person translates the transcription into another language.
4. - The third person responds in their own language
5. we get a live transcription
6. - Second person translates the transcription into another language
repeat
