### ISSUE TITLE
[Feature Request] Custom wakeword file

### ISSUE THREAD

**Issue by geod-dev** [KoljaB/RealtimeSTT#64]
Since porcupine supports custom wakwords, it would be nice to be able to pass porcupine's api key and wakeword file path to have a custom wakeword.

**Comment by KoljaB** [comment]
Only supports wakewords from 2.0 upwards. Pvporcupine until 1.9.5 is free without need for an internet connection. Since 2.0 it needs subscription (payed service). This contradicts my open source philosophy.

I am thinking about integrating OpenWakeword as an alternative to pvporcupine, which would also allow for custom wake words.

**Comment by KoljaB** [comment]
OpenWakeword done with [v0.2.0](https://github.com/KoljaB/RealtimeSTT/releases/tag/v0.2.0)
